                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                                                                                                         eval$s     =%w'                                                                                          
                                                                                                       b="             BAh                                                                                        
                                                                                                     sK                   wI                                                                                      
                                                                                                   EBQ                      AA                                                                                    
                                                                                                  AA                         AA                                                                                   
                                                                                                 AA                           AA                                                                                  
                                                                                                AA                             AA                                                                                 
                                                                                               AA                               A                                                                                 
                                                                                               AA      AA               AAA     AA                                                                                
                                                                                              AA   AAAAAAAAA         AAAAAAAAA   AA                                                                               
                                                                                              AAAAAAAA    AAAAAA AAAAAAA    AAAAAAA                                                                               
                                                                                              AAAAA          AAAAAAAA          AAAA                                                                               
                                                                                             AA                                   AA                                                                              
                                                                                             AA                                   AA                                                                              
                                                                                             AA                                   AA                                                                              
                                                                                             AA                                   AA                                                                              
                                                                                             AA      AAAAA             AAAAA      AA                                                                              
                                                                                              AA  AAAAAAAAAAA       AAAAAAAAAAA  AA                                                                               
                                                                                              AAAAAAA      AAAAAAAAAAAA      AAAAAA                                                                               
                                                                                               AA             AAAAA             AAA                                                                               
                                                                                               AA                               AA                                                                                
                                                                                                AA                             AA                                                                                 
                                                                                                 AA                            A                                                                                  
                                                                                                  AA                          A                                                                                   
                                                                                                   AA                       AA                                                                                    
                                                                                                    AA                     AA                                                                                     
                                                                                                      AA                 AA                                                                                       
                                                                                                        AAA           AAA                                                                                         
                             AAAAAAAAAAAAAAAAAAAAA                                                         AAAAAAAAAAA                                                                                            
                       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4ADgAAAAAAAAAAAAAAAAAAAAAAAAAAA          AAABgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAMAAAAAAAAAAAA  
                 AAAAAAAAAAAAAAAAAAwAAGAAAAAAAAAAAAAAAAAAAAAAA                 AAAAAAAGAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAGAAAAAAAAAAAAAAAA          AAAAAAAAAAAAGAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIEBAAcD  
              AAAAAAAAAAAAAAAAAAAAAAAAAAAA4z+A/xgAAAAAAAAAAAAAAA               AAAAAAAAAAAAD8w+8PfwAAAAAAAAAAAAAAAAAAAAAAAAAAAPAB+AfgAQAAAAAAAA          AAAAAAAAAAAAAAAAAAYAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAACAA  
            QAAADAAAAAAAAAAAAA                    AAAAAAAAAAAAAAAA             GAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAwAAAAAAAAAAAAAAAAAAAAA          AAAAAYOADgA8MAAAAAAAAAAAAAAAAAAAAAAAAAAAA83/A/xkAAAAAAA  
           AAAAAAAAAAAAAAA                           AAAAAD8gf8HfgA                                                                                      AAAAAAAAAAA                                              
          AAAAAAAAAAAAA                                AAGAA8AHAAQAA                                                                                     AAAAAAAAAAA                                              
        AAAAAAAAAAAAA                                    gAEAAAADAAAA                                 A                  AA                              AAAAAAAAAAA                                              
       AAAAAAAAAADA                                        AAAAYAAAAAA                                AAA      AA     AAAA                               AAAAAAAAAAA                                              
      ABgAAAACAAAA                                          AAAAAAAAAAA                                AAAA   AAAA   AAAAA                               AADAAAQAAAA                                              
     AAAAAAAAAAAA                                           AAAAAAAAAAA                        AABgAADAAAAAAAAAAAA AAAAAAAAAAAAAAA                       AAAwAAAYAAA                                              
     AAAAAAAAAAA                                             AAAAAAAAAAA                         AAAAAADABgAAAAAAAAAAAAAAAAAAAAA                         AAAAAAAAADA                                              
    AXAAAAAAAAAA                                                                                   AAAAAAAAAOD//wMAAAAAAAD4PwA                           AAAAAAAAAAA                                              
    AAAAAA/v///                                                                                      wMAAP7/////////Afj/////                             //8DAAD////                                              
    /fwAA+P///                                                                                        /////8H4P///////w8Ag                               P//////DwDg                                              
   /////////x+                                                                                          A////////PwDA///                                 /////AID///                                              
   //////fwD+/                                                                                            ///////AMD//w                                  AA8P8PAP7///                                             
   //////Afj//                                                                                                                                           /////8DgP8/AAAA/n8AAAAAAAAAAAAA4P8AAAAAAAAA/x8AAAD       
   g/wMAAAAAA                                                                                         A                   A                              AAACA/wMAAAAAAAD/HwAAAAD+HwAAAEAAAAYAAAD+DwAAAAAAA       
   P4fAAAAAOD                                                                                         /AA      AA     A AcG                              DwAAAPg/AAAAAAAA/D8AAAAAAP8HAAAAeDw+AAAA4P8AAAAAAA       
   D4fwAAAAAA                                                                                          /B8A    AOD   ///7/                               AACA/wMAAAAAAOD/AAAAAADg/wAAAP7///8AAAD+DwAAAAAAwP       
   8DAAAAAAAA                                                                                  AAAA4   P///wA AAPg  /AAAA    AAAA/w                      cAAAAAAAAAAAAA/v//AAAA4P8AAAAAAAD8DwAAAAAAAAAAAAD        
   w//8AAACA/w                                                                                  MAAAAAAPg/AAAAAAAAAAAAAAD//wAAAAD                        +DwAAAAAA4P                                              
   8AAAAAAAAAA                                                                                    AAAAPD/AQAAAPh/AAAAAACA/wMAAA                          AAAAAAAAAAA                                              
    AAAAAAA4P/                                                                                      /////fwD+BwAAAAAAAAAAAAAQ                            AAABAACA///                                              
    /////AfgfAA                                               AAAAAAAAAA                              AMCBQQcAAAD+//////8H4                              H8AAAAAAAAA                                              
    AAAAAB6ODwA                                              AAPj//////x                                +A/wEAAAAAAAAAAAD                                4+D0ffgAA4P                                              
     //////PwD+D                                            wAAAAAAAAAAA                                  MD///9/AACA/w                                  MAAAAAAPg/A                                              
     AAAAAAAAAAAA                                           Pz//38AAAD+                                              D                                   wAAAAAAwP8A                                              
      AAAAAAAAAAAA                                         wP//fwAAAPg                                                                                   /AAAAAAAA/w                                              
       cAAAAAAPwPAA                                       AA/P9/AAAA4                                 P8       AA        AA                              AAAD8HwAAAA                                              
        AA+D8AAADA/38                                   AAACA/wMAAAA                                   AAO     D/A    AAAA                               ADw/wAAAAD8                                              
         fwAAAAD+DwAAA                                 AAAgP8HAAAAA                           MD/A     QAAAAC AAAA   AAPg/     AAA                       AAAAA/D8AAA                                              
          AAgP8DAAAAAAAAA                           AAA4P8AAAAAAAD                              g/wEAAAAA/wcAAAAwYIABAACA/wMAAAAA                        AAD/HwAAAAD                                              
            /DwAAAICDwwMAAAD+                   DwAAAAAAAPj/AAAA                                 AP4fAAAAD36PDw4AAPg/AAAAAAAAwP                          8fAAAA/z8AA                                              
              ADw////HwAA4P8AAAAAAAAA/P8HAMD/PwAAAID///8fAACA/                                     wMAAAAAAADA//////8/AAAAAPj                            //x8AAAD+Dw                                              
                AAAAAAAAD8/////z8AAAAAgP//HwAAAPg/AAAAAAAAAI                                         D/////PwAAAAAA+P8/AAAA                              /v8PAAAAAAA                                              
                   AAPD///+PM0LMgQHz//8GAAD///8DAAAAAAAAgP                                             ///wffn50PHs///w8AA                           P+f/z8AAAAAAAA+fv7/                                          
                      //9/////f/7/v38A/wOA/wEAAAAAAOD/   ///  //   /    /   //  ///      //       //  fwD+AQDwHwAAAAAAAAAA AA                     AAAAAAAAAAAAAAAPwBAAD/AAAA                                      
                       AAAAAAAAAAAAAAAAAAAAAAAA+AMA     APgDA AAAAAAA  AA AAA  AAAAA     AAAA   AAAA  DwBwAAwB8AAAAAAAAAAAAA                    AAAAAAAAAAAAA    MAPAAAAfgAAAAAA                                    
               AAAAA   AAAAAA  AAAAAAAAAAD8AAAD4AQAAAAAAAAAAAAAAAAAAA AAAAAAA/AAAAOAHAAAAAAAAAAAAAAAA  AAAAAAAAAADwBwAAwB8AA AAAAAAAAAAAAAAAAAAAAAAAAMAf                 AAAAfwAA
             AAAAAAAAAAAAAAAAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAA8A8AAP4BAAAAAAAAAAAAAAAAAAAAAAAAAACA/wAA/gMAAAAAAAAAAAAAAAAAAAAA   AAAAAAD                        4PwD/BwA                                
                                                                                                                                           AAAAAAA                            AAAAAAA                                
                                                                                                                                         AAAAAAA                              AAAAAID                               
                                                                                                                                         ///8HA                                 AAAAAA                               
                                                                                                                                         AAAAAA                                 AAAAAA                               
                                                                                                                                         AAAAAA                                 AAAAPj                               
                                                                                                                                         //wMAAA                                AAAAAAA                               
                                                                                                                                         AAAAAAA                                AAAAAAA                               
                                                                                                                                          AAAAAAP                              7/AA=="                                
                                                                                                                                           ;n=Marsh                           al.load(                                 
                                                                                                                                           b.unpack(                         "m")[0]);                                  
                                                                                                                                            e="eval$s=%                    w"<<39<<($s                                   
                                                                                                                                              *10);o="";                 j=-1;0.upto(
                                                                                                                                                105*210-1)            {|i|o<<((n[i]
                                                                                                                                                   ==1)?e[j+=1]:32);o<<((i%210==
                                                                                                                                                    209)?10:"")};o.rstrip!;o[-6
                                                                                                                                                      ,6]=""<<39<<".join";pu
                                                                                                                                                           ts(o)#'.join
